# Basic
from pathlib import Path

import app_secrets


BACKEND_DIR = Path(__file__).resolve().parent
ARCHIVES_DIR = BACKEND_DIR / "archives"

# Local PostgreSQL configuration
POSTGRES_CONTAINER_NAME = "local-postgres"
POSTGRES_HOST = "localhost"
POSTGRES_PORT = 5432
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "xxs2IrVwlgrb5My2U"
POSTGRES_DB = "moonback2"
POSTGRES_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"

# Redis configuration
REDIS_URL = "redis://localhost"
REDIS_PORT = 6379
REDIS_DB = 0
REDIS_DEFAULT_TTL = 3600

# Qdrant configuration
QDRANT_API_KEY = "6bee818ccd7f5c8e8067530f6c3b623bfa675cc1700dd048f30312b6a1b7a6fd"
QDRANT_URL = "http://localhost"
QDRANT_PORT = 6333
QDRANT_GRPC_PORT = 6334
QDRANT_DIR = ARCHIVES_DIR / "qdrant_storage"
QDRANT_PREFER_GRPC = False
QDRANT_HTTPS = False
QDRANT_WECHAT_CHAT_RAG_COLLECTION_NAME = "wechat_chat_rag_collection"
WECHAT_RAG_RETRIEVAL_LIMIT = 10
WECHAT_RAG_RETRIEVAL_SCORE_THRESHOLD = 0.5
WECHAT_RAG_FINAL_EVIDENCE_LIMIT = 200
WECHAT_RAG_USEFUL_EVIDENCE_SCAN_BATCH_SIZE = 20


JINXI_SERVER_TMP_TOKEN = app_secrets.JINXI_SERVER_TMP_TOKEN
