"""
Update this file from CSV schemas in `backend/schemas/pg/`.
Each CSV is one PostgreSQL table. Preserve table/column names, map PostgreSQL
types to Python/Pydantic types, and respect `is_nullable` / primary keys.
Name generated classes as `Pg<TableName>`, for example `PgInvestigations`.
Do not edit the CSV files; they are generated by `backend/scripts/update_postgresql_schemas.py`.
"""

from typing import Any

from pydantic import BaseModel, Field


class PgInvestigations(BaseModel):
    investigation_id: int = Field(description="Primary key.")
    investigation_name: str = Field(default="")


class PgPoints(BaseModel):
    point_id: int = Field(description="Primary key.")
    point_type: str
    assumption: str = Field(default="")
    raw_data: dict[str, Any] = Field(default_factory=dict)
    conclusion: str = Field(default="")


__all__ = [
    "PgInvestigations",
    "PgPoints",
]
